### ISSUE TITLE
Irrecord error

### ISSUE THREAD

**Issue by Aurimaslu** [paulgration/node-infrared#2]
How fix this error:
irrecord: could not get file information for /dev/lirc
irrecord: default_init(): No such file or directory
irrecord: could not init hardware (lircd running ? --> close it, check permissions)

I try launch this code: 
var IRRecord = require('infrared').irrecord;

var irrecord = new IRRecord();
irrecord.on('stdout', function(data) {
  console.log(data);
});
irrecord.on('stderr', function(data) {
  console.log(data);
});
irrecord.on('exit', function() {
  // handle exit event
});
irrecord.start('remote', {disable_namespace: true});

**Comment by paulgration** [comment]
This looks like the standard output from irrecord when it can access the device. Does /dev/lirc definitely exist? And does the user account that is running node have access to the device? I think it would only need rw access.

**Comment by Aurimaslu** [comment]
No, its not exist /dev/lirc only /dev/lirc0. Yes i have access.

**Comment by paulgration** [comment]
Running 'irrecord -d /dev/lirc -n' from the command line, you are able to produce the same error I assume?
If your device is recognised as /dev/lirc0 then when you initialise the IRRecord object you would specify the device in the settings argument passed to it:

var irrecord = new IRRecord({device: '/dev/lirc0'});

**Comment by Aurimaslu** [comment]
I got this: irrecord: invalid argument count after: irrecord -d /dev/lirc -n. And i got new error, but i think this better:
irrecord: file "remote" does not contain valid data

**Comment by paulgration** [comment]
irrecord -d /dev/lirc -n nameofremotefile

**Comment by Aurimaslu** [comment]
irrecord: could not get file information for /dev/lirc
irrecord: default_init(): No such file or directory
irrecord: could not init hardware (lircd running ? --> close it, check permissions)

**Comment by paulgration** [comment]
So either /dev/lirc doesn't exist, perhaps it is /dev/lirc0 or your account doesn't have permissions to access it so you could try as root with sudo?

**Comment by Aurimaslu** [comment]
i try with sudo. Maybe i should set some settings or create file, because i install only lirc and node-infrared and then try your code get receive event.
