### ISSUE TITLE
Project still alive ? 

### ISSUE THREAD

**Issue by jaumard** [paulgration/node-infrared#3]
Is this project still maintain ? 4 years without update so I wonder if you are still behind the project or not :)

Thanks

**Comment by paulgration** [comment]
LIRC has moved on a bit since this was written but I don't think too much has changed, perhaps a few new options/features to add in. I haven't had much time to dedicate to this for a while but I'm sure I'll revisit it at some point. Feel free to contribute if you'd like!

**Comment by jaumard** [comment]
Thanks :) if you're available for some PR review and npm deployment I can try to contribute

**Comment by paulgration** [comment]
Sure, there is also [lirc_node](https://github.com/alexbain/lirc_node) which may be of interest. @alexbain and I started working on similar projects around the same time and have discussed a potential focused effort to merge together ideas and drive things forward a bit but I think we're both just lacking enough free time at the moment.

**Comment by jaumard** [comment]
I also take a look at this one (and ask same question lol) but I need both irsend and irrecord for my project and lirc_node doesn't support irrecord ^^
