### ISSUE TITLE
Example fo irrecord ? 

### ISSUE THREAD

**Issue by jaumard** [paulgration/node-infrared#4]
Is there any example on how to use this module with irrecord ? 

Because on the readme we can see : 
```
var IRRecord = require('infrared').irrecord;

var irrecord = new IRRecord();
irrecord.on('stdout', function(data) {
  console.log(data);
});
irrecord.on('stderr', function(data) {
  console.log(data);
});
irrecord.on('exit', function() {
  // handle exit event
});
irrecord.start('remote', {disable_namespace: true});
```
But there no mention on how set button names or go to the recording steps. Because by using this piece of code irrecord is showing PRESS ENTER to continue but  we can't ^^ 

Thanks :)

**Comment by paulgration** [comment]
It's just a wrapper around irrecord so what you see on stdout/stderr would be what you get as the output from the irrecord program (in the terminal). To "PRESS ENTER", you would make a call to `irrecord.write()` (which can take a string argument but always adds a '\n' for you, so without a string it is simulating the pressing of the enter key). When you later need to enter button names, you might use `irrecord.write('BTN_POWER');` for example. Hope this helps!

**Comment by jaumard** [comment]
I miss the `irrecord.write` ^^ perfect then thanks !
